services:
  mysql:
    image: mysql:8
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cron1
      MYSQL_USER: cron1
      MYSQL_PASSWORD: cron1
    volumes:
      - mysql_data_cron:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=3000000000



volumes:
  mysql_data_cron: